### ISSUE TITLE
如果我每次请求不重新创建okHttpClient对象,同域名切换IP时还能及时获取最新ip吗?

### ISSUE THREAD

**Issue by 258188170** [tencentyun/httpdns-android-sdk#10]

**Comment by httpdns** [comment]
同域名切换IP，指的是在权威DNS上域名解析配置更改吗？
客户端侧要感知到DNS解析配置更改，在解析配置更改前提下，需要旧的解析配置TTL过期，才能感知到。和是否更换OkHttpClient实例无关，OkHttp官方建议是最好维持一个单例Client的。
