### ISSUE TITLE
RSA算法 Android P 适配问题

### ISSUE THREAD

**Issue by Hollz** [tencentyun/httpdns-android-sdk#11]
Android P 上错误日志
E/System:  ******** DEPRECATED FUNCTIONALITY ********
E/System:  * The implementation of the KeyFactory.RSA algorithm from
E/System:  * the BC provider is deprecated in this version of Android.
E/System:  * It will be removed in a future version of Android and your
E/System:  * application will no longer be able to request it.  Please see
E/System:  * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
E/System:  * for more details.

beacon_android_xxxx

**Comment by httpdns** [comment]
感谢指正，beacon jar已经更新
